appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: wiBjpgJ8owhXQUqUhZP/GFNfMZ3Q4VgrQI726Ugi77R8r3REIb5n0+P4KyKx3z/nz6cNdq3PNLmCsCGUhk20A4Oodv9StuWODygrSC91KzZIgp2RX4i9fDeRe38Ug7wFoNk9EdsPopfJK28j+1HVh64iaiavK9aJmbRpUgCnjxRMSV4XtNJ0wlvhoTcjxmUdcINHrzX6D7KXf8L5t3o44O8iTVNYLDDushLu2Grhb3FZuX+BJGi3ShsJzSk3Zkr3GuJdY1vDvDDnDHz/EQDgNVlnzHXm58dadzeemfQCXH6CVFZGsfNOhpnImquWDE15dhziWTYN00R4UmN1hvn3r/tKadHx31qZ4J01NdGBN3I7Glxzu/lbP2RFVXJ1GVE6sdOeQQAIZGHqawbvJdX51X7h3iv761cRGOOCpXaGAdbu/5bMm4yOUiWoUn95mXUxArGyRM79jhImevZlpBHt/AvHAorQ48pbCejDv9bdWgfzRG0f4on9iPLNuR9wgUnc1Vauzfv4GSkXXq74gIb/vbSel1m59ayAnjE6kNUikMbz1dt4omLdL8i7rWNjv2BkeUMfofR9dFohWQfhPPBAL/H5WY2Mtf9xp8Lfjxsu1SN/oZmqqFlHWoG3BLVy/4iT9vw7i24TljOe0QlUk0QeOFwbocU62id80u3RWDQ2sJw=
conda_forge_output_validation: false
